version: 2.1

jobs:
  build_and_push_docker_image:
#    docker:
#      - image: alpine:3.7
    machine: true
    steps:
      - checkout
#      - run: apk update && apk upgrade && apk add --no-cache git docker openssh openrc
#      - run: rc-update add docker boot
      - run:
          name: build and push docker image
          command: |
            set -x
            REPO="https://github.com/Junyong-Suh/bitfront-telegram-bot.git"
            git clone $REPO
            cd bitfront-telegram-bot/
            LAST_GIT_TAG=$(git ls-remote --tags $REPO | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -n 1)
            DOCKER_HUB="zechery/bitfront-price-alert"
            NEW_IMAGE="${DOCKER_HUB}:${LAST_GIT_TAG}"
            docker build -t ${NEW_IMAGE} .
            docker push ${NEW_IMAGE}
  deploy:
#    docker:
#      - image: alpine:3.7
    machine: true
    steps:
      - checkout
#      - run: apk add --no-cache openssh
      - run:
          name: deploy new image
          command: |
            ssh ec2-user@ec2-3-101-40-44.us-west-1.compute.amazonaws.com -i bitfront-price-alert-on-telegram.pem ./circle.sh

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_push_docker_image
      - deploy:
          requires:
            - build_and_push_docker_image