version: 2.1

jobs:
  build_and_push_docker_image:
    machine: true
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            set -x
            REPO="https://github.com/Junyong-Suh/bitfront-telegram-bot.git"
            touch confidentials.py && echo "FOREIGN_WORKER_BOT_ID = \"${FOREIGN_WORKER_BOT_ID}\"" >> confidentials.py
            LAST_GIT_TAG=$(git ls-remote --tags $REPO | awk '{print $2}' | grep -v '{}' | awk -F"/" '{print $3}' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -n 1)
            NEW_IMAGE="zechery/bitfront-price-alert:${LAST_GIT_TAG}"
            docker login -u="$DOCKER_ID" -p="$DOCKER_PWD"
            docker build -t ${NEW_IMAGE} .
            docker push ${NEW_IMAGE}
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: deploy new image
          command: |
            ssh ec2-user@54.193.101.211 ./circle.sh

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_push_docker_image:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build_and_push_docker_image
          filters:
            branches:
              only: master